const movies = [
  {
    id: '020910b7-09d4-4bdb-9509-a716a112a036',
    title: 'Freaky',
    rating: 'R',
    length: '1h 43m',
    year: '2020',
    genre: 'Horror',
    description: 'After swapping bodies with a deranged serial killer, a young girl in high school discovers she has less than 24 hours before the change becomes permanent.',
    imdb_score: '6 / 10',
    rotten_tomato_score: '83',
    meta_critic_score: '66',
    trailer: 'https://www.youtube.com/embed/EqPnIcDW9g0',
    trailer_source: 'YouTube',
    trailer_owner: 'Universal Pictures',
    trailer_dt: 'Sep 10, 2020',
    poster: 'https://m.media-amazon.com/images/M/MV5BMTRkYmJlY2ItNmFlZi00OWVhLTg1ZTctOGE0MjM5ZGMwMmY4XkEyXkFqcGdeQXVyNjY1MTg4Mzc@._V1_UX182_CR0,0,182,268_AL_.jpg',
  },
  {
    id: 'c155054e-99c6-41b3-b5fc-674d7c933ad2',
    title: 'Up',
    rating: 'PG',
    length: '1h 36m',
    year: '2009',
    genre: 'Animation',
    description: '78-year-old Carl Fredricksen travels to Paradise Falls in his house equipped with balloons, inadvertently taking a young stowaway.',
    imdb_score: '8 / 10',
    rotten_tomato_score: '98',
    meta_critic_score: '88',
    trailer: 'https://www.youtube.com/embed/pkqzFUhGPJg',
    trailer_source: 'YouTube',
    trailer_owner: 'Walt Disney Studios',
    trailer_dt: 'Mar 12, 2009',
    poster: 'https://m.media-amazon.com/images/M/MV5BMTk3NDE2NzI4NF5BMl5BanBnXkFtZTgwNzE1MzEyMTE@._V1_UX182_CR0,0,182,268_AL_.jpg',
  },
];

export default movies;
